### ISSUE TITLE
saut de lignes non gardés

### ISSUE THREAD

**Issue by mthieu-yseop** [yseop/codequality#2]
si on a indenté le code avec des sauts de lignes, l'application du formatter les supprime.

Ex (dans StudioRepository) :

<pre>`collectPath(paths, gitCache.getFile(directoryPath, false),
                subFolderPath,
                includeInheritedItems,
                includeSubDirs,
                includeSubPackageItems,
                pathFilter,
                fileTypes);
`</pre>

devient 
<pre>`
collectPath(paths, gitCache.getFile(directoryPath, false), subFolderPath, includeInheritedItems, includeSubDirs, includeSubPackageItems,
                pathFilter, fileTypes);
`</pre>

**Comment by eborel-yseop** [comment]
Alors ca c'etait voulu en fait :sweat_smile: Le truc c'est que le formatter ne peux pas 'ignorer' un type de formattage et pas un autre. Si tu ecris une partie de ton code comme ca et pas une autre, le formatter va tout remettre comme on lui a dit, a savoir pour la grande majorite du code, de wrapper a partir de 150 caracteres.

On peut le forcer a mettre tout les arguments a la ligne, mais je trouve que ca rallonge pas mal la structure du code.

**Comment by mthieu-yseop** [comment]
hum, le soucis c'est que si on a aéré le code pour que ça soit plus lisible, le formatter va tout réduire sur le moins de ligne possible ... Je crois que Laurent était plus pour que le formatter ne soit pas "destructif' ...

**Comment by eborel-yseop** [comment]
Ba encore une fois, le but c'est d'avoir un code homogene, on ne peut pas garder le style de code de tout le monde et en meme temps avoir un code 'propre'. Tu peux toujours utilise les balise `@formatter:on/off` pour garder le formattage de ton code, mais ca risque de juste rendre l'utilisation d'un formatter inutile.

**Comment by lpetit-yseop** [comment]
Le but n'est-il pas aussi d'avoir un code plus clair (le compilo, il s'en fout à la rigueur, toute la classe sur une ligne ça lui irait aussi => le code doit être le plus lisible pour faciliter le dev et éviter les erreurs liées à des mauvaises interprétations du formatage qu'on a sous les yeux).

Est-il possible de dire au formatteur : "mon gars, c'est OK pour que tu exploses une ligne trop longue en plusieurs lignes, mais merci de ne pas faire de condensation de lignes. Bisous." ?

**Comment by lpetit-yseop** [comment]
Apparemment l'option existe et s'appelle `"Never join lines"`

**Comment by eborel-yseop** [comment]
Oui je fais des tests sur cette option.

**Comment by eborel-yseop** [comment]
Alors effectivement ca marche. Mais bon ca limite le cote "formattage et proprification" voulu je trouve. Ca permet d'avoir different style de code, ce qu'on voulait eviter a la base...

**Comment by eborel-yseop** [comment]
Bon j'ajoute le `Never join already wrapped lines`, a voir ce que ca donne en pratique. Mais si ca pousse les gens a faire n'importe quoi a ce niveau, je reproposerai de le mettre (en insistant beaucoup :grimacing: )

**Comment by mthieu-yseop** [comment]
je rouvre ce ticket, car le formatter re-condense les lignes sur une seule :
`@Suite.SuiteClasses({ 
    TestFirstUploadCompleteKb.class,
    TestOpenComplete.class, 
    TestAddAttributes.class, 
    TestReplaceAttributes.class })
public class TestYmlObjectEditorsSuite {`

devient
`@Suite.SuiteClasses({ TestFirstUploadCompleteKb.class, TestOpenComplete.class, TestAddAttributes.class, TestReplaceAttributes.class })
public class TestYmlObjectEditorsSuite {`

**Comment by mthieu-yseop** [comment]
ce qui "force" les gens à mettre des commentaires à la fin de chaque ligne :
`@Suite.SuiteClasses({ //
    TestFirstUploadCompleteKb.class, //
    TestOpenComplete.class, //
    TestAddAttributes.class, //
    TestReplaceAttributes.class })
public class TestYmlObjectEditorsSuite {`
ce que je trouve moyen ...

**Comment by eborel-yseop** [comment]
Yup, c'est normal :) Ca ete decide il y a un moment deja. Je n'ai pas touche au formatter depuis au moins un mois.

**Comment by lpetit-yseop** [comment]
Oui, s'il y a un "never join lines", je serai favorable à le remettre.
Autant on a besoin que l'indentation de la ligne soit toujours tip top, autant j'ai envie de continuer à avoir le dernier mot sur le formatteur quant à l'aération verticale

**Comment by eborel-yseop** [comment]
>Mais le fait que les gens le fassent (toute l'équipe YBS au moins est au courant, je l'ai appris comme cela, et j'ai l'impression que c'est en effet beaucoup utilisé) montre qu'il y a un souci…

Et dans mon ancienne boite personne ne faisait ca, et la norme pour le passage a la ligne (qui devait etre l'exception, etait fait avec un `//` en fin de ligne)  C'est ce qu'on a decide et mis en place ensemble dans le codequality. Si l'on change le formatter pour les preferences personnelles, autant arreter le formatter et revenir au far west qu'on avait avant.

D'autant plus que rajouter cette fonction entrainerait un reformattage de chaque fichier, comme au debut du codequality. Par exemple sur DialogApiController, ca me donne ca: 

https://i.imgur.com/krvgsbf.png

Donc a moins de vouloir a nouveau vous taper 200 diffs de formattage par fichier, je suggere que l'on reste a ce qui a ete decide (encore une fois avec tout le monde inclus dans le process).

**Comment by mthieu-yseop** [comment]
je me souviens pas de quand on a décidé cette règle de // pour forcer le formatteur à passer à la ligne
(en tout cas sur ce ticket, on avait parlé du never join lines au début)

je ne vois pas en quoi ne plus regrouper les lignes entrainerait un reformattage de chaque fichier :
si le fichier a été formatté et que les lignes sont regroupées sur une seule ligne, l'application du "nouveau" formatteur avec "never join lines" va laisser les lignes telles quelles (et le ne va pas les re-splitter), non ?

**Comment by eborel-yseop** [comment]
J'ai le souvenir de la discussion sur un chan public, avec Francois et Mael il me semble. Apres pour la retrouver, faudrait faire de la speleo... 

Et j'ai essaye toutes les options possible, il n'est pas possible de mettre en place ce comportement et de le faire cohabiter avec la longueur de ligne, il va par defaut tout realigner si cela fait moins que les 150 chars (sauf en activant le force split, ce qui du coup modifie l'integralite du fichier).

**Comment by mthieu-yseop** [comment]
pourtant, j'ai essayé 'never join already wrapped lines' qui a l'air de faire correctement son boulot

**Comment by eborel-yseop** [comment]
Oui effectivement je me concentrais plus precisement sur les Functions Calls, mais en activant le never join ca le fait pour tout. Ce qu'on avait decide de pas faire. Mais bon...
