### ISSUE TITLE
ajout de sauts de ligne sur commentaire en fin de ligne

### ISSUE THREAD

**Issue by mthieu-yseop** [yseop/codequality#3]
le formatter ajout des sauts de ligne sur les commentaires qui sont en fin de grand ligne :

ex :

<pre>`BdlFunctionTextualization func = new BdlFunctionTextualization(language, functionRoot, GrammaticalNumber.SINGULAR, Gender.UNDEFINED, args); // FIXME : verify number and gender ...`</pre>

devient 
<pre>`
BdlFunctionTextualization func = new BdlFunctionTextualization(language, functionRoot, GrammaticalNumber.SINGULAR, Gender.UNDEFINED, args); // FIXME
                                                                                                                                                    // :
                                                                                                                                                    // verify
                                                                                                                                                    // number
                                                                                                                                                    // and
                                                                                                                                                    // gender
                                                                                                                                                    // ...
`</pre>

**Comment by mthieu-yseop** [comment]
je pense qu'appliquer le formattage des commentaires // n'est pas forcément utile

**Comment by eborel-yseop** [comment]
Ah, je n'avais pas compris ton probleme dans ce sens. Pour le coup je ne suis pas d'accord. Les commentaires doivent etre formatte comme le reste, surtout que celui-ci est assez minime sur les `//`, a part la longueur de 130 colonnes, il n'y a pas grand chose de plus.

Pour ton exemple, c'est un faux probleme, le commentaire devrait etre au dessus de la methode.

**Comment by mthieu-yseop** [comment]
c'est dommage, car il y a pas mal de cas de ce tyle dans la codebase. (par ex des // FIXME ou // TODO en fin de ligne). ça va split les commentaires sur plusieurs lignes...

à minima, il n'y a pas possibilité de lui dire de splitter, mais de recommencer au début de la ligne dès la 2ème ligne ?

**Comment by eborel-yseop** [comment]
Non malheureusement ce n'est pas possible. Apres cela permettra de reperer facilement les endroits ou les commentaires malformes sont et de les fixes.
