### ISSUE TITLE
Incohérence checkstyle/formatteur pour balise `<p>`

### ISSUE THREAD

**Issue by lpetit-yseop** [yseop/codequality#5]
Petit souci entre checkstyle et le formatteur Eclipse, dans les javadocs, concernant la balise `<p>`: 
- checkstyle veut que `<p>` précède le texte, sans espace
- le formatage auto fait passer à la ligne le texte qui suit `<p>`

Ex., checkstyle voudrait ça :

```java
    /**
     * Adds an Appender to the log4j configuration.
     * 
     * <p>This method does not add the appender to any logger.
     */
```

et le formatteur me fait ça :

```java
    /**
     * Adds an Appender to the log4j configuration.
     * 
     * <p>
     * This method does not add the appender to any logger.
     */
```

**Comment by eborel-yseop** [comment]
[#PR-6](https://github.com/yseop/codequality/pull/6)
